language: haskell
install: cabal install 'certificate == 1.3.1'
script: "make ci"
notifications:
    irc:
        channels:
            - "irc.freenode.org#haskell-distributed"
        use_notice: true
    email:
        recipients:
            - cloud.haskell@gmail.com
